@startuml Diagramme de cas d'utilisation
left to right direction
skinparam style strictuml
skinparam packageStyle rect
skinparam backgroundcolor transparent
skinparam defaultfontname Verdana
actor Joueur as J
rectangle "Système" {
  (Jouer aux dés) as JP #powderblue
  (Redémarrer) as R #powderblue
  J -- JP
  J -- R
}
note right of JP
  Le joueur lance 3 dés.
  Le système calcule la somme.
  Le joueur gagne si la somme ≤ 10.
end note
@enduml


