@startuml RDCU pour redemarrerJeu
skinparam style strictuml
participant ":JeuDeDes" as JD
participant "joueurs: Map<String, Joueur>" as M

-> JD : redemarrerJeu()

note right JD
selon Contrôleur
(JeuDeDés est
l'objet racine)
end note

JD -> M : clear()

note right M
selon Expert
end note
@enduml
